<?php

namespace ContainerVV55ggJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ECOt6U5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.eCOt6U5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.eCOt6U5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'consultation' => ['privates', '.errored..service_locator.eCOt6U5.App\\Entity\\Consultation', NULL, 'Cannot autowire service ".service_locator.eCOt6U5": it references class "App\\Entity\\Consultation" but no such service exists.'],
        ], [
            'consultation' => 'App\\Entity\\Consultation',
        ]);
    }
}
