<?php

namespace ContainerVV55ggJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F7br8SiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f7br8Si' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f7br8Si'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dossiermedicalRepository' => ['privates', 'App\\Repository\\DossiermedicalRepository', 'getDossiermedicalRepositoryService', true],
        ], [
            'dossiermedicalRepository' => 'App\\Repository\\DossiermedicalRepository',
        ]);
    }
}
