<?php

namespace ContainerVV55ggJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O3zroEDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o3zroED' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o3zroED'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dossiermedical' => ['privates', '.errored..service_locator.o3zroED.App\\Entity\\Dossiermedical', NULL, 'Cannot autowire service ".service_locator.o3zroED": it references class "App\\Entity\\Dossiermedical" but no such service exists.'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'dossiermedical' => 'App\\Entity\\Dossiermedical',
            'entityManager' => '?',
        ]);
    }
}
