<?php

namespace ContainerVV55ggJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VtVWoj7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VtVWoj7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VtVWoj7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dossiermedical' => ['privates', '.errored..service_locator.VtVWoj7.App\\Entity\\Dossiermedical', NULL, 'Cannot autowire service ".service_locator.VtVWoj7": it references class "App\\Entity\\Dossiermedical" but no such service exists.'],
        ], [
            'dossiermedical' => 'App\\Entity\\Dossiermedical',
        ]);
    }
}
