<?php

namespace ContainerVV55ggJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getConsultationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.AXYi.zo.App\Entity\Consultation' shared service.
     *
     * @return \App\Entity\Consultation
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.AXYi.zo": it references class "App\\Entity\\Consultation" but no such service exists.');
    }
}
