<?php

namespace ContainerVV55ggJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossiermedical2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.o3zroED.App\Entity\Dossiermedical' shared service.
     *
     * @return \App\Entity\Dossiermedical
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.o3zroED": it references class "App\\Entity\\Dossiermedical" but no such service exists.');
    }
}
