<?php

namespace ContainerVV55ggJ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDossiermedicalService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VtVWoj7.App\Entity\Dossiermedical' shared service.
     *
     * @return \App\Entity\Dossiermedical
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.VtVWoj7": it references class "App\\Entity\\Dossiermedical" but no such service exists.');
    }
}
